spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  threads:
    virtual:
      enabled: true
  cassandra:
    keyspace-name: bezkoder
    contact-points: 127.0.0.1
    port: 9042